name: Build
# From now in android
# https://github.com/android/nowinandroid

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'app-ios/**'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-pr-number:
    if: github.event_name == 'pull_request'
    name: "get-pr-number"
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event.pull_request.number }}
        run: echo ok

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Check spotless
        run: ./gradlew spotlessCheck --stacktrace

      - name: Check lint
        run: ./gradlew lintDebug --stacktrace
#        continue-on-error: true # https://issuetracker.google.com/issues/241787635

      - name: Build all build type and flavor permutations
        run: ./gradlew assemble --stacktrace

      - name: Build zipline
        run: ./gradlew compileZipline --stacktrace

      - name: Run local tests
        run: ./gradlew testDebug --stacktrace

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: assemble-output
          path: app-android/build/outputs
          retention-days: 14

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: app-android/build/reports
          retention-days: 30
 

#  save computation resource for now
#  androidTest:
#    needs: build
#    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
#    timeout-minutes: 45
#    strategy:
#      matrix:
#        api-level: [ 23, 26, 30 ]
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Copy CI gradle.properties
#        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#
#      - name: Run instrumentation tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: ${{ matrix.api-level }}
#          arch: x86_64
#          disable-animations: true
#          disk-size: 1500M
#          heap-size: 512M
#          script: ./gradlew connectedDebugAndroidTest
#
#      - name: Upload test reports
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-reports
#          path: '*/build/reports/androidTests'

### Remove later; just for debugging
  test-stage-push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/checkout@v3
        with:
          repository: droidkaigi/conference-app-2021
          ref: gh-actions
          path: gh-actions
      - uses: actions/github-script@v3
        id: get-artifact-id
        with:
          result-encoding: string
          script: |
            const { data: resp } = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            })
            const artifact = resp.artifacts.find((a) => a.name === "assemble-output")

            if (artifact) {
              return artifact.id
            } else {
              return '[halt]'
            }
      - uses: ./gh-actions/actions/get-artifact
        id: get-artifact
        if: steps.get-artifact-id.outputs.result != '[halt]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-id: ${{ steps.get-artifact-id.outputs.result }}
          path: ~/assemble-output
      - run: >
          unzip ${{ steps.get-artifact.outputs.archive-path }} -d ~/assemble-output &&
          rm -f ${{ steps.get-artifact.outputs.archive-path }}
      - uses: ./gh-actions/actions/find-files
        id: find-dev-debug-apk
        with:
          pattern: "~/assemble-output/**/app-android-dev-debug.apk"
      - uses: jmatsu/dg-upload-app-action@v0.2
        id: upload
        with:
          app_owner_name: droidkaigi
          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          app_file_path: ${{ fromJSON(steps.find-dev-debug-apk.outputs.paths)[0] }}
          message: GitHub Actions have staged an artifact of ${{ github.ref }} / ${{ github.sha }}
          distribution_find_by: name
          distribution_id: ${{ format('staging/{0}', github.ref) }}
          release_note: ${{ format('[main] Workflow {0}/{1} based on {2}', github.run_id , github.run_number , github.sha) }}
          pin: false

  test-stage-pull-request:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/checkout@v3
        with:
          repository: droidkaigi/conference-app-2021
          ref: gh-actions
          path: gh-actions
      - uses: actions/github-script@v3
        id: get-pr
        with:
          script: |
            const { data: resp } = await github.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            })
            const job = resp.jobs.find((j) => j.name === "get-pr-number")

            if (job) {
              const { data: pull } = await github.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: job.steps[1].name
              })
              return pull
            } else {
              return '[halt]'
            }
      - uses: actions/github-script@v3
        id: get-artifact-id
        if: steps.get-pr.outputs.result != '[halt]'
        with:
          result-encoding: string
          script: |
            const { data: resp } = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            })
            const artifact = resp.artifacts.find((a) => a.name === "assemble-output")

            if (artifact) {
              return artifact.id
            } else {
              return '[halt]'
            }
      - uses: ./gh-actions/actions/get-artifact
        id: get-artifact
        if: steps.get-artifact-id.outputs.result != '[halt]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-id: ${{ steps.get-artifact-id.outputs.result }}
          path: ~/assemble-output
      - run: >
          unzip ${{ steps.get-artifact.outputs.archive-path }} -d ~/assemble-output &&
          rm -f ${{ steps.get-artifact.outputs.archive-path }}
      - uses: ./gh-actions/actions/find-files
        id: find-dev-debug-apk
        with:
          pattern: "~/assemble-output/**/app-android-dev-debug.apk"
      - uses: ./gh-actions/actions/create-deployment
        id: create-deployment
        with:
          github-token: ${{ github.token }}
          ref: refs/pull/${{ fromJSON(steps.get-pr.outputs.result).number }}/head
          sha: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }}
          artifact-name: assemble-output
          environment: deploygate-distribution
      - uses: jmatsu/dg-upload-app-action@v0.2
        id: upload
        continue-on-error: true
        with:
          app_owner_name: droidkaigi
          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          app_file_path: ${{ fromJSON(steps.find-dev-debug-apk.outputs.paths)[0] }}
          message: GitHub Actions have staged an artifact of ${{ fromJSON(steps.get-pr.outputs.result).number }}/head / ${{ fromJSON(steps.get-pr.outputs.result).head.sha }}
          distribution_find_by: name
          distribution_id: ${{ format('debug/refs/pull/{0}/head', fromJSON(steps.get-pr.outputs.result).number) }}
          release_note: ${{ format('Workflow {0}/{1} based on {2}', github.run_id , github.run_number , fromJSON(steps.get-pr.outputs.result).head.sha) }}
          pin: false
      - name: generate properties based on upload step's status
        id: deployment-properties
        if: steps.upload.conclusion == 'success'
        run: |
            if [[ "${{ steps.upload.outcome }}" == "success" ]]; then
              echo "::set-output name=deployment-url::${{ steps.upload.outputs.distribution_url }}"
              echo "::set-output name=description::Deployed an app successfully. Please try it through DeployGate!"
            else
              echo "::set-output name=deployment-url::$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
              echo "::set-output name=description::Staging an app failed. Please check the workflow."
            fi
      - uses: ./gh-actions/actions/commit-deployment
        if: steps.upload.conclusion == 'success'
        with:
          github-token: ${{ github.token }}
          deployment-id: ${{ fromJSON(steps.create-deployment.outputs.deployment).id }}
          state: ${{ steps.upload.outcome }}
          deployment-url: ${{ steps.deployment-properties.outputs.deployment-url }}
          description: ${{ steps.deployment-properties.outputs.description }}