name: Build
# From now in android
# https://github.com/android/nowinandroid

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'app-ios/**'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-pr-number:
    if: github.event_name == 'pull_request'
    name: "get-pr-number"
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event.pull_request.number }}
        run: echo ok

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Check spotless
        run: ./gradlew spotlessCheck --stacktrace

      - name: Check lint
        run: ./gradlew lintDebug --stacktrace
#        continue-on-error: true # https://issuetracker.google.com/issues/241787635

      - name: Build all build type and flavor permutations
        run: ./gradlew assemble --stacktrace

      - name: Build zipline
        run: ./gradlew compileZipline --stacktrace

      - name: Run local tests
        run: ./gradlew testDebug --stacktrace

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: assemble-output
          path: app-android/build/outputs
          retention-days: 14

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: app-android/build/reports
          retention-days: 30
  # stage default package only on push events (see stage-app.yml for pull_requests)
  stage-default:
    if: github.event_name == 'push'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: gh-actions
          path: gh-actions
      - uses: actions/download-artifact@v3
        with:
          name: assemble-output
          path: ~/assemble-output
      - uses: ./gh-actions/actions/find-files
        id: find-dev-debug-apk
        with:
          pattern: "~/assemble-output/**/app-android-dev-debug.apk"
      - uses: jmatsu/dg-upload-app-action@v0.2
        id: upload
        with:
          app_owner_name: droidkaigi
          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          app_file_path: ${{ fromJSON(steps.find-dev-debug-apk.outputs.paths)[0] }}
          message: GitHub Actions have staged an artifact of ${{ github.ref }} / ${{ github.sha }}
          distribution_find_by: name
          distribution_id: ${{ format('staging/{0}', github.ref) }}
          release_note: ${{ format('[main] Workflow {0}/{1} based on {2}', github.run_id , github.run_number , github.sha) }}
          pin: false

#  save computation resource for now
#  androidTest:
#    needs: build
#    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
#    timeout-minutes: 45
#    strategy:
#      matrix:
#        api-level: [ 23, 26, 30 ]
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Copy CI gradle.properties
#        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#
#      - name: Run instrumentation tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: ${{ matrix.api-level }}
#          arch: x86_64
#          disable-animations: true
#          disk-size: 1500M
#          heap-size: 512M
#          script: ./gradlew connectedDebugAndroidTest
#
#      - name: Upload test reports
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-reports
#          path: '*/build/reports/androidTests'
